--- !DirTarget
pathToTemplateModelsDirectory: filesTemplates/
directoryToSaveModels: manipulation/
directoryToExportModels: /tmp/output/
pathToProfile: smarty.profile.uml
pathToProfileConcern: concerns.profile.uml